"""
Sends the daily strategic digest via Gmail SMTP using an App Password.

Setup (one-time):
  1. Google Account → Security → 2-Step Verification (enable if not already)
  2. Google Account → Security → App passwords
  3. Generate a password for "Mail" → copy it into .env as GMAIL_APP_PASSWORD
"""

import os
import re
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send(briefing: str, notion_url: str = "") -> None:
    sender = os.environ["GMAIL_ADDRESS"]
    recipient = os.environ.get("DIGEST_RECIPIENT", sender)
    password = os.environ["GMAIL_APP_PASSWORD"]

    today = date.today().strftime("%B %d, %Y")
    subject = f"Your Strategic Digest — {today}"

    html = _to_html(briefing, notion_url, today)
    plain = briefing

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"Strategic Digest <{sender}>"
    msg["To"] = recipient
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())

    print(f"Email sent to {recipient}")


# ---------------------------------------------------------------------------
# Plain markdown → clean HTML email
# ---------------------------------------------------------------------------

_CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       background: #f9f9f9; color: #111; margin: 0; padding: 0; }
.wrap { max-width: 620px; margin: 32px auto; background: #fff;
        border-radius: 10px; padding: 36px 40px;
        box-shadow: 0 1px 4px rgba(0,0,0,.08); }
.header { border-bottom: 2px solid #7c3aed; padding-bottom: 16px; margin-bottom: 28px; }
.header h1 { font-size: 18px; color: #7c3aed; margin: 0; font-weight: 700; }
.header p  { font-size: 12px; color: #888; margin: 4px 0 0; }
h2 { font-size: 15px; font-weight: 700; color: #111; margin: 28px 0 10px;
     border-bottom: 1px solid #eee; padding-bottom: 6px; }
p  { font-size: 14px; line-height: 1.7; color: #333; margin: 8px 0; }
ul { padding-left: 18px; margin: 8px 0; }
li { font-size: 14px; line-height: 1.7; color: #333; margin: 4px 0; }
hr { border: none; border-top: 1px solid #eee; margin: 24px 0; }
.notion-btn { display: inline-block; margin-top: 24px; padding: 10px 18px;
              background: #7c3aed; color: #fff; border-radius: 6px;
              text-decoration: none; font-size: 13px; font-weight: 600; }
.footer { margin-top: 32px; font-size: 11px; color: #aaa; border-top: 1px solid #eee;
          padding-top: 16px; }
"""


def _to_html(markdown: str, notion_url: str, today: str) -> str:
    body_html = _md_to_html(markdown)

    notion_block = ""
    if notion_url:
        notion_block = f'<a class="notion-btn" href="{notion_url}">📄 View full briefing in Notion →</a>'

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>{_CSS}</style></head>
<body><div class="wrap">
<div class="header">
  <h1>Strategic Intelligence Digest</h1>
  <p>{today}</p>
</div>
{body_html}
{notion_block}
<div class="footer">Generated by your Strategic Digest agent.</div>
</div></body></html>"""


def _md_to_html(text: str) -> str:
    lines = text.splitlines()
    html_lines = []
    in_ul = False

    def close_ul():
        nonlocal in_ul
        if in_ul:
            html_lines.append("</ul>")
            in_ul = False

    for line in lines:
        stripped = line.rstrip()

        if stripped.startswith("## "):
            close_ul()
            html_lines.append(f"<h2>{_inline(stripped[3:])}</h2>")
        elif stripped.startswith("### "):
            close_ul()
            html_lines.append(f"<h3>{_inline(stripped[4:])}</h3>")
        elif stripped.startswith("---"):
            close_ul()
            html_lines.append("<hr>")
        elif stripped.startswith("- ") or stripped.startswith("• "):
            if not in_ul:
                html_lines.append("<ul>")
                in_ul = True
            html_lines.append(f"<li>{_inline(stripped[2:])}</li>")
        elif stripped == "":
            close_ul()
        else:
            close_ul()
            html_lines.append(f"<p>{_inline(stripped)}</p>")

    close_ul()
    return "\n".join(html_lines)


def _inline(text: str) -> str:
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", text)
    return text
